name: Build Source Tests
on:
  workflow_dispatch:
  push:
    branches: [trunk]
  pull_request:
    branches: [trunk]

permissions: # added using https://github.com/step-security/secure-repo
  contents: read

jobs:
  atsdk:
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Install atsdk
        run: cmake -S . -B build -DCMAKE_C_COMPILER=gcc \
          -DCMAKE_C_FLAGS="-Wall -Wextra -Werror-implicit-function-declaration" \
          -DCMAKE_COMPILE_WARNING_AS_ERROR=true

      - name: Build atsdk
        run: sudo cmake --build build --target install

      - name: Build sample_cmake_project
        working-directory: examples/desktop/sample_cmake_project
        run: |
          cmake -S . -B build -Datsdk="/usr/local/bin/cmake/atsdk"
          cmake --build build

      - name: Run sample_cmake_project executable
        working-directory: examples/desktop/sample_cmake_project
        run: |
          ./build/main
