name: Build REPL
on:
  pull_request:
    branches: [trunk]

jobs:
  unit-tests:
    runs-on: "windows-latest"
    steps:
      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
      # - name: CMake Configure, Make Install, and CTest
      #   uses: threeal/cmake-action@v1.3.0
      #   with:
      #     source-dir: packages/${{ matrix.package }}
      #     generator: Unix Makefiles
      #     # args: -D$(echo "${{ matrix.package }}" | tr '[:lower:]' '[:upper:]')_BUILD_TESTS=ON # this doesn't work :/
      #     args: -DATCLIENT_BUILD_TESTS=ON -DATCHOPS_BUILD_TESTS=ON
      #     build-dir: packages/${{ matrix.package }}/build
      #     run-build: true
      #     build-args: --target install
      #     run-test: false
      #     # run-test: true
      #     # test-args: -V --output-on-failure

      - name: MbedTLS
        run: |
          git clone https://github.com/Mbed-TLS/mbedtls.git
          cd mbedtls
          cmake -S . -B build -DWINDOWS=1 -DWINDOWS_BUILD=1
          cmake --build build --target install

      - name: CMake Configure
        working-directory: packages/atclient
        run: |
          cmake -S . -B build -DATCLIENT_FETCH_ATCHOPS=ON -DATCLIENT_FETCH_MBEDTLS=OFF

      - name: Build and Install (Windows)
        working-directory: packages/atclient
        run: |
          cmake --build build --config Debug

      - name: Build REPL
        working-directory: packages/repl
        run: |
          cmake -S . -B build
          cmake --build build --target install
