name: Build Source Tests
on:
  workflow_dispatch:
  push:
    branches: [trunk]
  pull_request:
    branches: [trunk]

permissions: # added using https://github.com/step-security/secure-repo
  contents: read

jobs:
  atsdk:
    strategy:
      fail-fast: true
      matrix:
        include:
          - cc: "gcc"
            cflags: "-Wall -Wextra -Werror-implicit-function-declaration"
          - cc: "clang"
            cflags: "-Wall -Wextra -Werror-implicit-function-declaration"
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Show compiler version
        run: ${{ matrix.cc }} --version

      - name: Install atsdk
        run: cmake -S . -B build -DCMAKE_C_COMPILER="${{ matrix.cc }}" \
          -DCMAKE_C_FLAGS="${{ matrix.cflags }}" \
          -DCMAKE_COMPILE_WARNING_AS_ERROR="on"

      - name: Show CMake Cache Variables
        run: cmake -L -N -S . -B build

      - name: Build atsdk
        run: cmake --build build

      - name: Install atsdk
        run: sudo cmake --build build --target install

      - name: Build sample_cmake_project
        working-directory: examples/desktop/sample_cmake_project
        run: |
          cmake -S . -B build -Datsdk="/usr/local/bin/cmake/atsdk"
          cmake --build build

      - name: Run sample_cmake_project executable
        working-directory: examples/desktop/sample_cmake_project
        run: |
          ./build/main
