name: Unit Tests
on:
  push:
    branches: [trunk]
  pull_request:
    branches: [trunk]

jobs:
  unit-tests:
    runs-on: "ubuntu-latest"
    continue-on-error: true # if one matrix cell fails, the other ones keep going :)
    strategy:
      matrix:
        package: [atchops, atclient]

    steps:
      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3

      - name: CMake Configure
        working-directory: packages/${{matrix.package}}
        run: |
          cmake -S . -B build -DATCLIENT_BUILD_TESTS=ON -DATCHOPS_BUILD_TESTS=ON

      - name: Build and Install
        working-directory: packages/${{matrix.package}}
        run: |
          sudo cmake --build build --target install

      - name: CTest
        working-directory: packages/${{ matrix.package}}/build/tests
        run: |
          ctest -V --output-on-failure --timeout 2
