name: Tests
on:
  push:
    branches: [trunk]
  pull_request:
    branches: [trunk]

jobs:
  build:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@8f4b7f84864484a7bf31766abe9204da3cbe65b3 # v3.5.0

      - name: AtChops
        uses: threeal/cmake-action@v1.3.0
        with:
          source-dir: packages/atchops
          build-dir: packages/atchops/build
          generator: Unix Makefiles
          args: -DATCHOPS_BUILD_TESTS=ON
          run-build: true
          run-test: true

      - name: AtClient
        uses: threeal/cmake-action@v1.3.0
        with:
          source-dir: packages/atclient
          build-dir: packages/atclient/build
          generator: Unix Makefiles
          args: -DATCLIENT_BUILD_TESTS=ON
          run-build: true
          run-test: true

