name: Unit Tests (AtChops Windows)
on:
  pull_request:
    branches: [trunk]

jobs:
  unit-tests:
    runs-on: "windows-latest"
    steps:
      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3

      - name: Clone MbedTLS
        run: |
          git clone https://github.com/Mbed-TLS/mbedtls.git

      - name: Config MbedTLS
        working-directory: mbedtls
        run: |
          cmake -S . -B build -DWINDOWS=1 -DWINDOWS_BUILD=1

      - name: Config MbedTLS
        working-directory: mbedtls
        run: |
          cmake --build build --target install

      - name: CMake Configure AtChops
        working-directory: packages/atchops
        run: |
          cmake -S . -B build -DATCHOPS_BUILD_TESTS=ON

      - name: Build and Install AtChops
        working-directory: packages/atchops
        run: |
          cmake --build build --config Debug

      - name: Run Tests
        working-directory: packages/repl/build/tests
        run: |
          ctest --output-on-failure -V -C Debug
