name: Unit Tests
on:
  push:
    branches: [trunk]
  pull_request:
    branches: [trunk]

jobs:
  unit_tests:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3

      - name: atchops - CMake Configure
        working-directory: packages/atchops
        run: |
          cmake -S . -B build -DATCHOPS_BUILD_TESTS=ON -DCMAKE_INSTALL_PREFIX=./install

      - name: atchops - Build with Unix Makefiles
        working-directory: packages/atchops
        run: |
          cmake --build build --target install

      - name: atchops - Run CTest
        working-directory: packages/atchops/build/tets
        run: |
          ctest -V

      - name: atclient - CMake Configure
        working-directory: packages/atclient
        run: |
          cmake -S . -B build -DATCLIENTS_BUILD_TESTS=ON -DCMAKE_INSTALL_PREFIX=./install

      - name: atclient - Build with Unix Makefiles
        working-directory: packages/atclient
        run: |
          cmake --build build --target install

      - name: atclient - Run CTest
        working-directory: packages/atclient/build/tets
        run: |
          ctest -V
