name: Unit Tests
on:
  workflow_dispatch:
  push:
    branches: [trunk]
  pull_request:
    branches: [trunk]

permissions:  # added using https://github.com/step-security/secure-repo
  contents: read

jobs:
  unit-tests:
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633 # v4.1.2

      - name: Install AtChops
        working-directory: packages/atchops
        run: |
          cmake -S . -B build -DATCHOPS_BUILD_TESTS=ON
          sudo cmake --build build --target install

      - name: CTest AtChops
        working-directory: packages/atchops/build/tests
        run: |
          ctest -V --output-on-failure --timeout 2

      - name: Install AtClient
        working-directory: packages/atclient
        run: |
          cmake -S . -B build -DATCLIENT_BUILD_TESTS=ON
          sudo cmake --build build --target install

      - name: CTest AtClient
        working-directory: packages/atclient/build/tests
        run: |
          ctest -V --output-on-failure --timeout 10
